test_files:
  # Each of these Accuri files has roughly the same set of problems
  # - DATA offset end is 1 too high
  # - STEXT doesn't exist but overlaps with TEXT (and is weirdly very different)
  # - contains $VOL and $SPILLOVER yet is 3.0 and not 3.1
  # - in some case DATA in TEXT is wildly off (its safe to ignore since HEADER
  #   is correct)
  - name: Accuri - C6.fcs
    options:
      ignore_stext: true
      version_override: FCS3.1
      data_correction: [0, -1]
      text_data_correction: [0, -1]

  - name: Accuri - C6 - A01 H2O.fcs
    options:
      prim_text_correction: [0, -1]
      ignore_stext: true
      data_correction: [0, -1]
      allow_header_text_offset_mismatch: true
      version_override: FCS3.1

  - name: Accuri - C6 - A02 Spherotech 8 Peak Beads.fcs
    options:
      ignore_stext: true
      prim_text_correction: [0, -1]
      data_correction: [0, -1]
      allow_header_text_offset_mismatch: true
      version_override: FCS3.1

  - name: Accuri - C6 - A03 HPB - CD45 PerCP.fcs
    options:
      ignore_stext: true
      prim_text_correction: [0, -1]
      data_correction: [0, -1]
      allow_header_text_offset_mismatch: true
      version_override: FCS3.1

  - name: 1 WT_001.fcs
    options:
      # second DATA offset is 0
      squish_offsets: true
      # offsets have whitespace
      trim_value_whitespace: true
      # STEXT duplicates TEXT
      ignore_stext: true
      # BYTEORD is should only be 2 bytes
      integer_byteord_override: [1,2]
    
  - name: 3215apc 100004.fcs
    options:
      integer_byteord_override: [3,2,1]
    
  - name: Applied Biosystems - Attune.fcs
    options:
      # has weird trailing space after TEXT
      prim_text_correction: [0, -9]
      # this TEXT has blanks
      use_literal_delims: true
      allow_empty: true

  - name: BD - FACS Aria II.fcs
    options:
      # analysis has -1 for end
      allow_negative: true
      # this file also has $P14DISPLAY, not only which is deviant (the right
      # keyword is $PnD) but it's version is 3.0 not 3.1. It also isn't the
      # correct value ("LIN" vs "Linear,0,0")
      allow_pseudostandard: true
      
  # this one seems near perfect except for the offset spacing thing, lots of
  # keys are also only whitespace so blanks need to be allowed
  - name: BD - FACS Aria II - Compensation Controls_B515 Stained Control.fcs
    options:
      trim_value_whitespace: true
      allow_empty: true

  # ditto
  - name: BD - FACS Aria II - Compensation Controls_G560 Stained Control.fcs
    options:
      trim_value_whitespace: true
      allow_empty: true

  # ditto
  - name: BD - FACS Aria II - Compensation Controls_G610 Stained Control.fcs
    options:
      trim_value_whitespace: true
      allow_empty: true

  # ditto
  - name: BD - FACS Aria II - Compensation Controls_G660 Stained Control.fcs
    options:
      trim_value_whitespace: true
      allow_empty: true

  # DATA offset for this is way beyond end of file, which ff currently
  # doesn't check
  # - name: BD - FACS Aria II - Compensation Controls_G710 Stained Control.fcs
  #   options:
  #     trim_value_whitespace: true
  

  - name: Beckman Coulter - Cyan.fcs
    options:
      other_width: 10
      # dreaded PnE log issue
      fix_log_scale_offsets: true
      integer_byteord_override: [1,2]
      # DATA offsets in TEXT are wrong
      allow_header_text_offset_mismatch: true

  - name: Beckman Coulter - Cytomics FC500.LMD
    options:
      use_literal_delims: true
      # offsets are apparently systemically off
      prim_text_correction: [0, -1]
      data_correction: [0, -1]
      # this file has a known issue in that the CXP software uses 10 for PnB
      # when the actual width is 16
      integer_widths_from_byteord: true
      # has lots of DFCxTOy stuff, and mysterious kws like $RUNNUMBER and
      # $INSTADDRESS
      allow_pseudostandard: true

  - name: Beckman Coulter - Gallios.LMD
    options:
      # lots of DFCxTOy keys (which don't even match $PAR), and also $PnG
      allow_pseudostandard: true
      # PnE has space in front of it
      trim_value_whitespace: true
      # trimming spaces results in lots of blank keys
      allow_empty: true
      
  # this parses fine but spews tons of warnings. Some are for dropping keys
  # that are parsed as ints but should be floats (ie ff is wrong), will also
  # freak out that PnB is one greater than 2^32-1
  - name: Beckman Coulter - MoFlo Astrios - linear settings.fcs
    options:
      other_width: 14

  # ditto
  - name: Beckman Coulter - MoFlo Astrios - log settings.fcs
    options:
      other_width: 14

  # suffers from PnE log X,0 error
  - name: Beckman Coulter - MoFlo XDP.fcs
    options:
      other_width: 14
      fix_log_scale_offsets: true

  - name: Cytek DxP10 - 6-peak Q&b 11-06-2012 001.fcs
    options: {}

  - name: Cytek DxP10 - APC COMP BEADS011.fcs
    options: {}

  - name: Cytek DxP10 - BLANK COMP BEADS007.fcs
    options: {}
    
  - name: Cytek DxP10 - FITC COMP BEADS008.fcs
    options: {}
    
  - name: Cytek DxP10 - PERCP COMP BEADS010.fcs
    options: {}
    
  - name: Cytek DxP10 - PE COMP BEADS009.fcs
    options: {}
    
  - name: MVa2011-06-30_fcs30.fcs
    options: {}
    
  - name: MVa2011-06-30_fcs30c.fcs
    options: {}
    
  - name: MVa2011-06-30_fcs31.fcs
    options:
      prim_text_correction: [0, -1]
      supp_text_correction: [0, -1]
      data_correction: [0, -1]
      text_data_correction: [0, -1]
      # not sure what OTHER is doing here, it looks like STEXT
      max_other: 0
    
  # ...???
  - name: Millipore - easyCyte 6HT-2L - InCyte.fcs
    options:
      prim_text_correction: [0, 1]
      # IDK, it looks like some of these kws are xml blobs
      allow_non_ascii_keywords: true
      allow_odd: true
      allow_pseudostandard: true
      allow_header_text_offset_mismatch: true
      allow_missing_final_delim: true
    
  - name: Miltenyi Biotec - MACSQuant Analyzer.fcs
    options: {}

  - name: Partec - PAS - 8 peak beads.FCS
    options:
      data_correction: [0, -1]
      integer_byteord_override: [1,2]
      # $INST/$FIL
      allow_pseudostandard: true

  - name: Stratedigm - S1400 - 8 Peaks Beads.fcs
    options:
      # this is a (rare?) example of a 3.1 file that uses variable bit width;
      # ...good thing I added this to FF :) Time channel is 32 and rest are 16
      version_override: FCS3.1
    
  - name: System II listmode with extra info in bits D10-D15.LMD
    options:
      # $TIME (which is 300, so probably not $TIME(STEP))
      allow_pseudostandard: true
      
  - name: Verity Software House - GemStoneGeneratedData - 500000events.fcs
    options: {}
  
  - name: iCyt - Eclipse.lmd
    options:
      version_override: FCS3.1
      # $ETIME (they probably meant $ETIM)
      allow_pseudostandard: true

  # ditto
  - name: iCyt - Eclipse - 8 peak.lmd
    options:
      version_override: FCS3.1
      allow_pseudostandard: true
    
  - name: iCyt - Eclipse - 20100922_14h35m49s(Protocol CytoTrol, Well C7).lmd
    options:
      version_override: FCS3.1
      allow_pseudostandard: true
    
  - name: iCyt - Eclipse - 20100923_12h23m41s(Protocol Cell Cycle DAPI , SampleID1 DAPI Prep-DNA, Well A1).lmd
    options:
      version_override: FCS3.1
      allow_pseudostandard: true
    
  - name: iCyt - Eclipse - 20100924_08h32m40s(Protocol AlignCheck - Final Test 6Runs, Well A1).lmd
    options:
      version_override: FCS3.1
      allow_pseudostandard: true
